name: Immigration GPT CI

python:
  version: 3.10

scripts:
  - echo "✅ Running TOC segmenter..."
  - python segment_by_toc.py test_docs/sample.pdf test_docs/sample_toc.json

  - echo "✅ Running OCR segmenter..."
  - python final_ocr_segments.py

  - echo "✅ Running summarizer..."
  - python summarize_docs.py test_docs/segmented/

tests:
  - name: Check segments_text.json exists
    run: test -f segments_text.json
    
