[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "immigration-gpt-api"
version = "0.0.0"
description = "Internal utilities and FastAPI backend"
dependencies = []
