services:
  - type: web
    name: immigration-gpt-api
    env: python
    plan: free

    buildCommand: |
      # 1) make apt available and install tesseract‑ocr
      apt-get update && apt-get install -y tesseract-ocr
      # 2) install Python deps
      pip install -r requirements.txt

    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
