name: Codex CI Modernize

on:
  pull_request:
    branches: ['clean/doc-intel', 'main']
  push:
    branches: ['clean/doc-intel']

jobs:
  codex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip
          pip install pytest
          npm ci

      - name: Codex refactor (quiet auto-edit)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npx codex -a auto-edit --quiet "update README with project overview"

      - name: Run smoke tests
        run: pytest -q
